### PR TITLE
Branch2

### PR DESCRIPTION
**Pull request by robertoostenveld**

### CODE REVIEW

**Comment by Horschig** [comment]
greetings from me, too! Hope life is good for you!

**Comment by robertoostenveld** [comment]
> greetings from me, too! Hope life is good for you!

Oh, are you following this repository? 

I am messing around with continuous integration, and have to re-run the same one again and again to get it to work.

**Comment by robertoostenveld** [comment]
ok, good enough for now.

**Comment by schoffelen** [comment]
image

**Comment by Horschig** [comment]
> > greetings from me, too! Hope life is good for you!
> 
> Oh, are you following this repository?
> 
> I am messing around with continuous integration, and have to re-run the same one again and again to get it to work.

haha yea, I know the pain. I set up quite a few of actions for us in the past year. It's both fun and a massive time sink. But in the end, it's just super nice to see things automated (for us now the changelog is automatically made incl. versions of dependencies, unit tests are automatically run, packages are automatically made, and uploaded to a github release and comments are made to issues that can be tested after every PR). 

I was actually surprised that I am following this repo here ;)

**Pull request merged**
